### ISSUE TITLE
Browser icon missing in Wall of Fame page

### ISSUE THREAD

**Issue by judy-n** [JLambertazzo/wpgbingo#23]
The browser icon disappears when I visit the Wall of Fame:

![Screen Shot 2024-02-21 at 10 03 53 PM](https://github.com/JLambertazzo/wpgbingo/assets/64036735/3ccbe729-6958-4d6a-beb3-2dae047cd356)

**Comment by JLambertazzo** [comment]
Oops!

**Comment by JLambertazzo** [comment]
Fixed by [7823ee2](https://github.com/JLambertazzo/wpgbingo/commit/7823ee26a83af5c1b7315c9e8208f8d4fe04f5f4)
